from __future__ import annotations

from .catalog import (
    BOTTOM_BRIDGE,
    BOTTOM_ELBOW_KNEE_ESCAPE,
    BOTTOM_RESPONSE_FOREARM_FRAME,
    BOTTOM_RESPONSE_TIGHT_ELBOW_ARM_DEFENSE,
    BOTTOM_RESPONSE_TURN_IN_RECOVERY,
    BOTTOM_TRAP_AND_ROLL_ESCAPE,
    TOP_AMERICANA_ARM_ISOLATION,
    TOP_CROSSFACE_PRESSURE,
    TOP_HIGH_MOUNT_CLIMB,
    TOP_RESPONSE_HIP_FOLLOW_REPUMMEL,
    TOP_RESPONSE_POST_AND_BASE,
    TOP_RESPONSE_WIDE_MOUNT_BASE,
)
from ...domain.matchup import MatchupTable
from ...domain.model import Grade


RAW_GRADES: dict[tuple[str, str], Grade] = {
    (TOP_HIGH_MOUNT_CLIMB, BOTTOM_RESPONSE_FOREARM_FRAME): Grade.SUCCESS,
    (TOP_HIGH_MOUNT_CLIMB, BOTTOM_RESPONSE_TURN_IN_RECOVERY): Grade.CONTESTED,
    (TOP_HIGH_MOUNT_CLIMB, BOTTOM_RESPONSE_TIGHT_ELBOW_ARM_DEFENSE): Grade.FAILURE,
    (TOP_CROSSFACE_PRESSURE, BOTTOM_RESPONSE_FOREARM_FRAME): Grade.FAILURE,
    (TOP_CROSSFACE_PRESSURE, BOTTOM_RESPONSE_TURN_IN_RECOVERY): Grade.SUCCESS,
    (TOP_CROSSFACE_PRESSURE, BOTTOM_RESPONSE_TIGHT_ELBOW_ARM_DEFENSE): Grade.STRONG_SUCCESS,
    (TOP_AMERICANA_ARM_ISOLATION, BOTTOM_RESPONSE_FOREARM_FRAME): Grade.STRONG_SUCCESS,
    (TOP_AMERICANA_ARM_ISOLATION, BOTTOM_RESPONSE_TURN_IN_RECOVERY): Grade.CONTESTED,
    (TOP_AMERICANA_ARM_ISOLATION, BOTTOM_RESPONSE_TIGHT_ELBOW_ARM_DEFENSE): Grade.STRONG_FAILURE,
    (BOTTOM_BRIDGE, TOP_RESPONSE_POST_AND_BASE): Grade.STRONG_FAILURE,
    (BOTTOM_BRIDGE, TOP_RESPONSE_WIDE_MOUNT_BASE): Grade.FAILURE,
    (BOTTOM_BRIDGE, TOP_RESPONSE_HIP_FOLLOW_REPUMMEL): Grade.SUCCESS,
    (BOTTOM_ELBOW_KNEE_ESCAPE, TOP_RESPONSE_POST_AND_BASE): Grade.STRONG_SUCCESS,
    (BOTTOM_ELBOW_KNEE_ESCAPE, TOP_RESPONSE_WIDE_MOUNT_BASE): Grade.SUCCESS,
    (BOTTOM_ELBOW_KNEE_ESCAPE, TOP_RESPONSE_HIP_FOLLOW_REPUMMEL): Grade.STRONG_FAILURE,
    (BOTTOM_TRAP_AND_ROLL_ESCAPE, TOP_RESPONSE_POST_AND_BASE): Grade.STRONG_FAILURE,
    (BOTTOM_TRAP_AND_ROLL_ESCAPE, TOP_RESPONSE_WIDE_MOUNT_BASE): Grade.FAILURE,
    (BOTTOM_TRAP_AND_ROLL_ESCAPE, TOP_RESPONSE_HIP_FOLLOW_REPUMMEL): Grade.STRONG_SUCCESS,
}

MOUNT_MATCHUPS = MatchupTable.build(RAW_GRADES)


def raw_grade(action_id: str, response_id: str) -> Grade:
    try:
        return MOUNT_MATCHUPS.grade(action_id, response_id)
    except ValueError as exc:
        raise ValueError(f"No Mount v0 lookup entry for {action_id!r} vs {response_id!r}") from exc
